#include <mathematics.h>
#include <greeting.h>
#include <iostream>
//#include <boost/date_time/posix_time/posix_time.hpp>

/**
 * Get the current time, as a string
 * @return the current time
 */
//auto currentTime() {
//  auto today = boost::posix_time::second_clock::local_time();
//  return boost::posix_time::to_simple_string(today);
//}
/**
 * The actual main function. This will output four different lines:
 * * A greeting, as generated by the greeting() function from the static Library
 * * The current date and time, as generated by Boost DateTime
 * * The result of adding two numbers, as calculated by the add() function from the shared Library
 * * The result of multiplying two numbers, as calculated by the multiply() function from the shared Library
 */
int main(void) {
  std::cout << greeting("C++ Build Systems") << std::endl;
  //std::cout << "Running at: " << currentTime() << std::endl;
  std::cout << "1 + 1 = " << add(1, 1) << std::endl;
  std::cout << "2 * 3 = " << multiply(2, 3) << std::endl;
  return 0;
}
